/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacio;

import CapaDomini.Domini;
import CapaDomini.Partida.Help;
import CapaDomini.Tauler.GeneratorController;
import CapaDomini.Tauler.Hidato;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Pau
 */
public class FrameNewGameType extends javax.swing.JFrame {

    private final Domini parent;
    /**
     * Creates new form FrameNewGameType
     */
    public FrameNewGameType(Domini parent) {
        initComponents();
        if (parent == null) this.parent = new Domini();
        else this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savedHidatoButton = new javax.swing.JButton();
        savedGameButton = new javax.swing.JButton();
        randomHidatoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        savedHidatoButton.setText("Jugar hidato guardat");
        savedHidatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedHidatoButtonActionPerformed(evt);
            }
        });

        savedGameButton.setText("Continuar partida guardada");
        savedGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedGameButtonActionPerformed(evt);
            }
        });

        randomHidatoButton.setText("Jugar hidato aleatori");
        randomHidatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomHidatoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(savedHidatoButton)
                    .addComponent(savedGameButton)
                    .addComponent(randomHidatoButton))
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(savedHidatoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savedGameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomHidatoButton)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savedHidatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedHidatoButtonActionPerformed
        this.setVisible(false);
        parent.obrirLlista(this);
    }//GEN-LAST:event_savedHidatoButtonActionPerformed

    private void savedGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedGameButtonActionPerformed
        this.setVisible(false);
        parent.obrirLlistaPartides(this);
    }//GEN-LAST:event_savedGameButtonActionPerformed

    private void randomHidatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomHidatoButtonActionPerformed
        //public FrameGame(Domini parent, RankingController rc, HidatoUserController uc, GameManagerController gmc, Help h, String gameName)
        Object[] options = { "Baix", "Mitja","Alt" };
        int val = JOptionPane.showOptionDialog(null, "Click OK to continue", "Warning",
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options,options[0]);
        Help h;
        if (val == 0) h = Help.LOW;
        else if (val == 1) h = Help.MEDIUM;
        else h = Help.HIGH;
        GeneratorController hidatoGen = new GeneratorController();
        //x, y aleatoris entre 3 i 8 (inclosos)
        Random rand = new Random();
        int x = rand.nextInt(5)+3;
        int y = rand.nextInt(5)+3;
        Hidato hidato = hidatoGen.generateHidato(x,y);
        parent.obrirPartida(this, h, "",hidato);
    }//GEN-LAST:event_randomHidatoButtonActionPerformed

    private void msgError(String text) {
        JOptionPane.showMessageDialog(this,text,"Error",JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameNewGameType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameNewGameType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameNewGameType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameNewGameType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameNewGameType(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton randomHidatoButton;
    private javax.swing.JButton savedGameButton;
    private javax.swing.JButton savedHidatoButton;
    // End of variables declaration//GEN-END:variables
}
