/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacio;

import CapaDomini.Usuari.HidatoUserController;
import javax.swing.JOptionPane;
import CapaDomini.Misc.Fonts;
import CapaDomini.Partida.GameManagerController;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;


/**
 * Vista que permet fer login al programa, registrar nous usuaris, i entrar
 * com a convidat
 * @author David
 */
public class FrameLogin extends javax.swing.JFrame {

    /*
     * Controladors necessaris
     */
    private HidatoUserController uc;
    private GameManagerController gmc;
    
    /*
     * Controlador AdminVistes per obrir noves pantalles
     */
    private AdminVistes parent;
    
    /*
     * Creadora amb parametres
     * Posa el LookAndFeel "Windows" i configura els camps de username i
     * password perquè intentin entrar al pitjar Enter
     */
    public FrameLogin(AdminVistes parent, HidatoUserController uc, GameManagerController gmc) {
        this.parent = parent;
        this.uc = uc;
        this.gmc = gmc;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {}
        initComponents();
        setIconImage((new ImageIcon("icon.png")).getImage());
        jPasswordField1.addKeyListener(new KeyListener() {
            @Override
            public void keyReleased (KeyEvent evt) { }
            @Override
            public void keyPressed (KeyEvent evt) { }
            @Override
            public void keyTyped (KeyEvent evt) {
                if (evt.getKeyChar() == '\n') {
                    entra();
                }
            }
        });
        jTextField1.addKeyListener(new KeyListener() {
            @Override
            public void keyReleased (KeyEvent evt) { }
            @Override
            public void keyPressed (KeyEvent evt) { }
            @Override
            public void keyTyped (KeyEvent evt) {
                if (evt.getKeyChar() == '\n') {
                    entra();
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Identifica't");
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(Fonts.getFont("OpenSans-Light", Font.PLAIN, 18));
        jLabel1.setText("Nom d'usuari");

        jTextField1.setFont(Fonts.getFont("OpenSans-Light", Font.PLAIN, 18));
        jTextField1.setToolTipText("");

        jLabel2.setFont(Fonts.getFont("OpenSans-Light", Font.PLAIN, 18));
        jLabel2.setText("Contrasenya");

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(Fonts.getFont("OpenSans-Light", Font.PLAIN, 18));
        jButton1.setText("Entra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(Fonts.getFont("OpenSans-Light", Font.PLAIN, 18));
        jButton2.setText("Entra com a convidat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(Fonts.getFont("OpenSans-Light", Font.PLAIN, 18));
        jButton3.setText("Registra't");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(Fonts.getFont("OpenSans-Light", Font.PLAIN, 36));
        jLabel3.setText("Inici de sessió / Registre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Es crida al pitjar el botó Entra
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        entra();
    }//GEN-LAST:event_jButton1ActionPerformed

    /*
     * Es crida al pitjar el botó Entra com a Convidat
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        entraConvidat();
    }//GEN-LAST:event_jButton2ActionPerformed

    /*
     * Es crida al pitjar el botó Registra't
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        registrar();
    }//GEN-LAST:event_jButton3ActionPerformed

    /*
     * Intenta fer login amb les dades dels camps username i password
     * Si falta alguna dada, ho explicita
     * Si no es pot fer login, n'explica el motiu
     * Si es pot fer login, inicialitza el gameSet amb aquest usuari i crida la
     * funció obrirMenu de l'AdminVistes
     */
    private void entra() {
        String username = jTextField1.getText();
        String password = new String(jPasswordField1.getPassword());
        jPasswordField1.setText("");
        if (username.equals("")) {
            msgError("Falta nom d'usuari");
        }
        else if (password.equals("")) {
            msgError("Falta contrasenya");
        }
        else {
            int result = uc.login(username, password);
            if (result == -1) msgError("L'usuari no existeix");
            else if (result == -2) msgError("Contrasenya incorrecta");
            else if (result == -3) msgError("Error desconegut");
            else {
                JOptionPane.showMessageDialog(this,"Has entrat correctament","Fantàstic!",JOptionPane.INFORMATION_MESSAGE);
                gmc.initGameSet();
                parent.obrirMenu(this);
            }
        }
    }
    
    /*
     * Entra al programa en mode convidat
     */
    private void entraConvidat() {
        JOptionPane.showMessageDialog(this,"Entraràs com a convidat. Algunes funcions no estaran disponibles.","Fantàstic!",JOptionPane.INFORMATION_MESSAGE);
        parent.setConvidat();
        parent.obrirMenu(this);
    }
    
    /*
     * Intenta registrar l'usuari amb les dades dels camps username i password
     * Si falta alguna dada, ho explicita
     * Si no es pot fer el registre, n'explica el motiu
     * Si es pot fer registre, ho explicita
     */
    private void registrar() {
        String username = jTextField1.getText();
        String password = new String(jPasswordField1.getPassword());
        jPasswordField1.setText("");
        if (username.equals("")) {
            msgError("Falta nom d'usuari");
        }
        else if (username.contains("/") || username.contains("*")) {
            msgError("Els caràcters '/' i '*' no són valids per al nom");
        }
        else if (username.equals("Convidat")) {
            msgError("Nom d'usuari no disponible");
        }
        else if (password.equals("")) {
            msgError("Falta contrasenya");
        }
        else {
            int result = uc.createUser(username, password);
            if (result == -1) msgError("L'usuari ja existeix");
            else if (result == -2) msgError("Error desconegut");
            else {
                JOptionPane.showMessageDialog(this,"Usuari creat correctament","Fantàstic!",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    
    /*
     * Mostra un missatge d'error amb la informació text
     */
    private void msgError(String text) {
        JOptionPane.showMessageDialog(this,text,"Error",JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
