/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistes;

import domini.Partida.Difficulty;
import domini.Rank.RankingController;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillem
 */
public class FrameRanking extends javax.swing.JFrame {
    
    private RankingController rc;

    /**
     * Creates new form FrameRanking
     */
    public FrameRanking() {
        initComponents();
        N = RankingController.getRankingMaxSize();
        inicialitza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorDificultat = new javax.swing.JComboBox();
        labelDificultat = new javax.swing.JLabel();
        rankingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ranking");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        selectorDificultat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fàcil", "Mitjà", "Dificil" }));
        selectorDificultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorDificultatActionPerformed(evt);
            }
        });

        labelDificultat.setText("Selecciona la dificultat:");

        rankingPanel.setName("Ranking"); // NOI18N
        rankingPanel.setLayout(new java.awt.GridLayout(20, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDificultat)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(selectorDificultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rankingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelDificultat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorDificultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(472, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rankingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelDificultat.getAccessibleContext().setAccessibleName("jLabel1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msgError(String text) {
        JOptionPane.showMessageDialog(this,text,"On vas flipat!",JOptionPane.ERROR_MESSAGE);
    }
    
    private void selectorDificultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorDificultatActionPerformed
        String selection = selectorDificultat.getSelectedItem().toString();
        switch (selection) {

            case "Fàcil": 
                setVisibleRanking(Difficulty.EASY);
                break;

            case "Mitjà":
                setVisibleRanking(Difficulty.MEDIUM);
                break;

            case "Dificil":
                setVisibleRanking(Difficulty.HARD);
                break;
                
            default:
                setVisibleRanking(Difficulty.HARD);
        }
    }//GEN-LAST:event_selectorDificultatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRanking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDificultat;
    private javax.swing.JPanel rankingPanel;
    private javax.swing.JComboBox selectorDificultat;
    // End of variables declaration//GEN-END:variables

    private ArrayList <ArrayList <JLabel> > entrades;
    
    private final int N;
    
    public void setRc(RankingController rc) {
        this.rc = rc;
    }
    
    private void inicialitza() {
        rc = new RankingController(); //Solo para debugar (luego se elimina)
        rc.init(); //Solo para debugar (luego se elimina)
        rankingPanel.setLayout(new GridLayout(N,3));
        for (int i = 0; i < N; ++i) {
            for (int j = 0; j < 3; ++j) {
                rankingPanel.add(new JLabel)
            }
        }
    }
    
    private void setVisibleRanking(Difficulty dif) {
        rankingPanel.setLayout(new GridLayout(20,1));
        ArrayList <String> rank = rc.getRankingInfo(dif);
        for (int i = 0; i < rank.size(); ++i) {
            rankingPanel.add(new JLabel((i+1) + ". " + rank.get(i)));
        }
        for (int i = rank.size(); i < 20; ++i) {
            rankingPanel.add(new JLabel(""));
        }
    }
    

}
