/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistes;


import domini.Misc.Colors;
import domini.Tauler.HidatoManagerController;
import domini.Tauler.HidatoSet;
import java.awt.Color;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author David
 */
public class FrameEditor extends javax.swing.JFrame {

    /**
     * Creates new form FrameEditor
     */
    public FrameEditor() {
        initComponents();
        inici(8,8);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        b_canvi_num = new javax.swing.JRadioButton();
        b_canvi_type = new javax.swing.JRadioButton();
        b_canvi_prop = new javax.swing.JRadioButton();
        panel_type = new javax.swing.JPanel();
        b_blank = new javax.swing.JRadioButton();
        b_given = new javax.swing.JRadioButton();
        b_void = new javax.swing.JRadioButton();
        panel_num = new javax.swing.JPanel();
        b_esborrar_num = new javax.swing.JRadioButton();
        b_preguntar_num = new javax.swing.JRadioButton();
        b_seq_num = new javax.swing.JRadioButton();
        spinner_num_actual = new javax.swing.JSpinner();
        l_num_actual = new javax.swing.JLabel();
        panel_nom = new javax.swing.JPanel();
        textfield_nom = new javax.swing.JTextField();
        b_canvia_nom = new javax.swing.JButton();
        label_nom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcions d'edició"));

        b_canvi_num.setText("Canviar número");

        b_canvi_type.setText("Canviar tipus de cel·la");

        b_canvi_prop.setText("Canviar propietats");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_canvi_num)
                    .addComponent(b_canvi_type)
                    .addComponent(b_canvi_prop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(b_canvi_num)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_canvi_type)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_canvi_prop))
        );

        panel_type.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipus de cel·la"));

        b_blank.setText("Cel·la blanca");

        b_given.setText("Cel·la donada");

        b_void.setText("Cel·la no vàlida");

        javax.swing.GroupLayout panel_typeLayout = new javax.swing.GroupLayout(panel_type);
        panel_type.setLayout(panel_typeLayout);
        panel_typeLayout.setHorizontalGroup(
            panel_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_typeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_blank)
                    .addComponent(b_given)
                    .addComponent(b_void))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_typeLayout.setVerticalGroup(
            panel_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_typeLayout.createSequentialGroup()
                .addComponent(b_blank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_given)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_void))
        );

        panel_num.setBorder(javax.swing.BorderFactory.createTitledBorder("Acció:"));

        b_esborrar_num.setText("Esborrar número");

        b_preguntar_num.setText("Preguntar número");

        b_seq_num.setText("Seqüència de números");

        l_num_actual.setText("Número actual:");

        javax.swing.GroupLayout panel_numLayout = new javax.swing.GroupLayout(panel_num);
        panel_num.setLayout(panel_numLayout);
        panel_numLayout.setHorizontalGroup(
            panel_numLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_numLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_numLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_numLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(l_num_actual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinner_num_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b_esborrar_num)
                    .addComponent(b_preguntar_num)
                    .addComponent(b_seq_num))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_numLayout.setVerticalGroup(
            panel_numLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_numLayout.createSequentialGroup()
                .addComponent(b_esborrar_num)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_preguntar_num)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_seq_num)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_numLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_num_actual)
                    .addComponent(spinner_num_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_nom.setBorder(javax.swing.BorderFactory.createTitledBorder("Canvi de nom"));

        b_canvia_nom.setText("Canvia el nom");

        javax.swing.GroupLayout panel_nomLayout = new javax.swing.GroupLayout(panel_nom);
        panel_nom.setLayout(panel_nomLayout);
        panel_nomLayout.setHorizontalGroup(
            panel_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfield_nom)
                    .addComponent(b_canvia_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_nomLayout.setVerticalGroup(
            panel_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nomLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textfield_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_canvia_nom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        label_nom.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        label_nom.setText("Hidato:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b_blank;
    private javax.swing.JRadioButton b_canvi_num;
    private javax.swing.JRadioButton b_canvi_prop;
    private javax.swing.JRadioButton b_canvi_type;
    private javax.swing.JButton b_canvia_nom;
    private javax.swing.JRadioButton b_esborrar_num;
    private javax.swing.JRadioButton b_given;
    private javax.swing.JRadioButton b_preguntar_num;
    private javax.swing.JRadioButton b_seq_num;
    private javax.swing.JRadioButton b_void;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel l_num_actual;
    private javax.swing.JLabel label_nom;
    private javax.swing.JPanel panel_nom;
    private javax.swing.JPanel panel_num;
    private javax.swing.JPanel panel_type;
    private javax.swing.JSpinner spinner_num_actual;
    private javax.swing.JTextField textfield_nom;
    // End of variables declaration//GEN-END:variables

    // =============================AQUI LO MEU=================================

    
    
    private ArrayList<ArrayList<SquareCell>> panels;
    private ArrayList<ArrayList<JLabel>> labels;
    private HidatoManagerController hmc;
    private ButtonGroup g1, g2, g3;
    private String nomHidato;
    private Color fons = new Color(0x0C0C0C); // negre
    private Color blanc = new Color(fons.getRGB()^0xFFFFFF);
    private Color color1 = new Color(0xC40D2A); // granate
    private Color color2 = new Color(0x780088); // lila fluix
    private Color color3 = new Color(0x550088); // lila fort
    private Color color4 = new Color(0x3E88DE); // blau fluix
    
    
    
    public void inici(int N, int M) {
        HidatoSet hs = new HidatoSet();
        hmc = new HidatoManagerController(hs, null);
        hmc.createRandom(N, M);
        label_nom.setText("Hidato sense nom");
        panels = new ArrayList<>();
        
        int maxim, N1, N2, M1, M2;
        maxim = Math.max(N,M);
        N1 = (maxim-N)/2;
        N2 = N + N1;
        M1 = (maxim-M)/2;
        M2 = M + M1;
        jPanel1.setLayout(new GridLayout(maxim, maxim));
        
        System.out.print(label_nom.getFont().getFontName()+"\n");
        for (int i0 = 0; i0 < maxim; ++i0) {
            panels.add(new ArrayList<>());
            for (int j0 = 0; j0 < maxim; ++j0) {
                if (N1 <= i0 && i0 < N2 && M1 <= j0 && j0 < M2) {
                    int i = i0-N1, j = j0-M1;
                    int val = hmc.getTempCellVal(i,j);
                    domini.Tauler.Type type = hmc.getTempCellType(i,j);
                    SquareCell p = new SquareCell(i,j,val,type,blanc,Color.GRAY,color1,Colors.negre, 500/maxim*5/10,true);
                    panels.get(i).add(p);
                    jPanel1.add(p, i0*maxim+j0);
                    p.changeType(hmc.getTempCellType(i,j));
                    p.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                            mousePress((SquareCell) evt.getComponent());
                        }
                        @Override
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                            mouseRelease((SquareCell) evt.getComponent());
                        }
                    });
                }
                else {
                    JPanel p = new JPanel();
                    jPanel1.add(p,i0*maxim+j0);
                }
                
            }
        }
        
        g1 = new ButtonGroup();
        g1.add(b_canvi_num); g1.add(b_canvi_type); g1.add(b_canvi_prop);
        g2 = new ButtonGroup();
        g2.add(b_blank); g2.add(b_given); g2.add(b_void);
        g3 = new ButtonGroup();
        g3.add(b_esborrar_num); g3.add(b_preguntar_num); g3.add(b_seq_num);
        
        b_canvi_num.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                totInvisible();
                panel_num.setVisible(true);
            }
        });
        b_canvi_type.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                totInvisible();
                panel_type.setVisible(true);
            }
        });
        b_canvi_prop.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                totInvisible();
                panel_nom.setVisible(true);
            }
        });
        
        b_esborrar_num.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                l_num_actual.setEnabled(false);
                spinner_num_actual.setEnabled(false);
            }
        });
        b_preguntar_num.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                l_num_actual.setEnabled(false);
                spinner_num_actual.setEnabled(false);
            }
        });
        b_seq_num.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                l_num_actual.setEnabled(true);
                spinner_num_actual.setEnabled(true);
            }
        });
        spinner_num_actual.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent evt) {
                if ((Integer) spinner_num_actual.getValue() <= 0) {
                    spinner_num_actual.setValue(1);
                }
            }
        });
        spinner_num_actual.setValue(1);
        
        
        b_canvia_nom.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String name = textfield_nom.getText();
                if (hmc.usedName(name)) {
                    msgError("Ja existeix un hidato amb aquest nom");
                }
                else if (name.replace(" ", "").equals("")) {
                    msgError("Nom no vàlid");
                }
                else {
                    nomHidato = name;
                    label_nom.setText("Hidato: "+name);
                }
            }
        });
        
        totInvisible();
        //canviarColors(this);
    }
    
    private void canviarColors(Container c) {
        try {
            ((SquareCell) c).getA();
        }
        catch(Exception e1) {
            try {
                ((Container)c).setBackground(blanc);
            }
            catch (Exception e) {}
            try {
                ((Container)c).setForeground(fons);
            }
            catch (Exception e) {}
            try {
                Border d = ((JPanel)c).getBorder();
                ((TitledBorder)d).setTitleColor(fons);
            }
            catch (Exception e) {}
            try {
                ((JButton)c).setForeground(fons);
            }
            catch(Exception e) {}
        }
        
        int n = c.getComponentCount();
        for (int i = 0; i < n; ++i) {
            try {
                canviarColors((Container)c.getComponent(i));
            }
            catch(Exception e) {}
        }
    }
    
    private void totInvisible() {
        panel_type.setVisible(false);
        g2.clearSelection();
        panel_num.setVisible(false);
        g3.clearSelection();
        l_num_actual.setEnabled(false);
        spinner_num_actual.setEnabled(false);
        panel_nom.setVisible(false);
    } 
    
    private void mousePress (SquareCell p) {
        if (b_canvi_num.isSelected() || b_canvi_type.isSelected()) p.setLight(true);
    }
    
    private void mouseRelease (SquareCell p) {
        if (p.getLight()) {
            if (b_canvi_num.isSelected() && p.getType() != domini.Tauler.Type.VOID) {
                canviarNum(p);
            }
            else if (b_canvi_type.isSelected()) {
                canviarType(p);
            }
            p.setLight(false);
        }
    }
    
    private void canviarNum (SquareCell p) {
        int num = -2;
        if (b_esborrar_num.isSelected()) {
            num = 0;
        }
        else if (b_preguntar_num.isSelected()) {
            try {
                String input = JOptionPane.showInputDialog("Escriu un número:");
                if (input == null) return;
                num = Integer.parseInt(input);
                if (num <= 0) num = -1;
            }
            catch (Exception e) {
                num = -1;
            }
        }
        else if (b_seq_num.isSelected()) {
            num = (Integer) spinner_num_actual.getValue();
            spinner_num_actual.setValue(num+1);
        }
        if (num == -1) msgError("Número no vàlid");
        else if (num == -2) msgError("Selecciona una opció");
        else {
            hmc.setTempCellVal(p.getA(), p.getB(), num);
            p.changeVal(num);
        }
    }
    
    private void canviarType (SquareCell p) {
        if (b_blank.isSelected()) {
            hmc.setTempCellType(p.getA(), p.getB(), domini.Tauler.Type.BLANK);
            p.changeType(domini.Tauler.Type.BLANK);
        }
        else if (b_given.isSelected()) {
            hmc.setTempCellType(p.getA(), p.getB(), domini.Tauler.Type.GIVEN);
            p.changeType(domini.Tauler.Type.GIVEN);
        }
        if (b_void.isSelected()) {
            hmc.setTempCellType(p.getA(), p.getB(), domini.Tauler.Type.VOID);
            hmc.setTempCellVal(p.getA(), p.getB(), -1);
            p.changeType(domini.Tauler.Type.VOID);
            p.changeVal(0);
        }
    }
    
    private void msgError(String text) {
        JOptionPane.showMessageDialog(this,text,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
