/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistes;


import domini.Misc.Colors;
import domini.Tauler.Cell;
import domini.Tauler.GeneratorController;
import domini.Tauler.Hidato;
import domini.Tauler.HidatoManagerController;
import domini.Tauler.Type;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;

/**
 *
 * @author David
 */
public class FrameEditor extends javax.swing.JFrame {

    /**
     * Creates new form FrameEditor
     */
    public FrameEditor() {
        initComponents();
        inici(5,5);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    // =============================AQUI LO MEU=================================

    
    
    ArrayList<ArrayList<SquareCell>> panels;
    ArrayList<ArrayList<JLabel>> labels;
    Hidato h;
    
    public void inici(int N, int M) {
        
        GeneratorController gc = new GeneratorController();
        h = new Hidato(N, M);
        panels = new ArrayList<>();
        
        jPanel1.setLayout(new GridLayout(N, M));
        
        for (int i = 0; i < N; ++i) {
            panels.add(new ArrayList<>());
            for (int j = 0; j < M; ++j) {
                SquareCell p = new SquareCell(i,j);
                p.setColors(color(i,j),Colors.vermell, Colors.blau_fosc);
                panels.get(i).add(p);
                jPanel1.add(p);
                p.omplir(h.getCell(i,j));
                p.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        mouseIn((SquareCell) evt.getComponent());
                    }
                    @Override
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        mouseOut((SquareCell) evt.getComponent());
                    }
                    @Override
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        mousePress((SquareCell) evt.getComponent());
                    }
                    @Override
                    public void mouseReleased(java.awt.event.MouseEvent evt) {
                        mouseRelease((SquareCell) evt.getComponent());
                    }
                });
                
            }
        }
        
        
    }
    
    private void mouseIn (SquareCell p) {
        p.setBorder(new BevelBorder(BevelBorder.LOWERED));
    }
    
    private void mouseOut (SquareCell p) {
        p.setBorder(new BevelBorder(BevelBorder.RAISED));
        p.setLight(false);
    }
    
    private void mousePress (SquareCell p) {
        p.setLight(true);
    }
    
    private void mouseRelease (SquareCell p) {
        if(p.getLight()) {
            String input = JOptionPane.showInputDialog(null);
            try {
                int num = Integer.parseInt(input);
                h.getCell(p.getA(), p.getB()).setVal(num);
                p.omplir(h.getCell(p.getA(), p.getB()));
            }
            catch (Exception e) {
                msgError("No és un número");
            }
            p.setLight(false);
        }
    }
    
    private Color color (int i, int j) {
        if ((i+j)%2 == 0) return Colors.blau_fluix;
        return Colors.blanc;
    }
    
    private void msgError(String text) {
        JOptionPane.showMessageDialog(this,text,"Error",JOptionPane.ERROR_MESSAGE);
    }
}
